management:
  server:
    port: 8081
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
  metrics:
    tags:
      application: ${spring.application.name:message-platform}
      environment: prod

logging:
  config: classpath:logback-spring.xml
spring:
  profiles:
    active: local
  lifecycle:
    timeout-per-shutdown-phase: 5s
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 40MB
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    properties:
      hibernate:
        '[order_inserts]': true
        '[order_update]': true

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://1.234.42.151:3306/WEB?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: wisecan
    password: wisecanwistabase
    hikari:
      connection-timeout: 8000
      max-lifetime: 480000
      idle-timeout: 300000
      keepalive-time: 180000
      minimum-idle: 5
      maximum-pool-size: 13

  data:
    redis:
      host: localhost
      port: 6379
      password: redispass